# Import Numpy

In [2]:
import numpy as np


# 1D array

In [2]:
a= np.array(([1,2,3]))

In [3]:
a

array([1, 2, 3])

# shape
(rows, columns)

In [4]:
a.shape #shows info about row and column

(3,)

# dimension

In [5]:
a.ndim #returns the dimsnion of the array

1

# 2D array

In [6]:
b= np.array(
    [[2,3,4], [4,5,6]] #double bracket symbllizes 2D
)

In [7]:
b

array([[2, 3, 4],
       [4, 5, 6]])

In [8]:
b.shape


(2, 3)

In [9]:
b.ndim

2

# 3D Array

In [10]:
c=np.array([[[1,2,3],
          [4,5,6]]])

In [11]:
c

array([[[1, 2, 3],
        [4, 5, 6]]])

In [12]:
c.shape

(1, 2, 3)

In [13]:
c.ndim

3

# Data Type

In [14]:
a.dtype,b.dtype,c.dtype #dtype shows us the data type of the given array

(dtype('int64'), dtype('int64'), dtype('int64'))

In [15]:
d1=np.array(([1,2,3]))#1D
d2=np.array(([[1,2,3]]))#2D
d3=np.array(([[[1,2,3]]]))#3D


In [16]:
d=d1,d2,d3

In [17]:
d

(array([1, 2, 3]), array([[1, 2, 3]]), array([[[1, 2, 3]]]))

In [18]:
f=np.array(([1.5,2.4,3.2]))

In [19]:
f

array([1.5, 2.4, 3.2])

In [20]:
f.dtype #float type

dtype('float64')

# Elements

In [5]:
c=np.array([[[1,2,3],
          [4,5,6]]])

### size

In [6]:
c.size #how many elements are there in the array (rows + columns)

6

### item size

In [23]:
c.itemsize #how many bytes they consume

8

### total size

In [24]:
c.nbytes # (size * item size)

48

# Memory Allocation

In [25]:
c.nbytes #how many bytes consumed by array

48

# Array Creation

In [26]:
arr=np.array([4,5,6],dtype='int' )

In [27]:
arr

array([4, 5, 6])

# Array Sum

In [8]:
list1=[1,2,3]
list2=[4,5,6]

print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [13]:
arr1=np.array([10,20,30])
arr2=np.array([4,5,6])
print(arr1+arr2)


[14 25 36]


array* 40%

In [16]:
arr1*0.4

array([ 4.,  8., 12.])

# zeros

In [28]:
zeros=np.zeros((2,2),dtype='int')  

In [29]:
zeros

array([[0, 0],
       [0, 0]])

In [30]:
zeros=np.zeros((3,2),dtype='float')  

In [31]:
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# ones

In [32]:
ones=np.ones((3,2))  #dtype default float

In [33]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# full

In [34]:
np.full ((2,3),5) # np.full((shape), element)

array([[5, 5, 5],
       [5, 5, 5]])

In [18]:
np.full (5,10.0) #iteration, value

array([10., 10., 10., 10., 10.])

### Value of your own

In [22]:
spurs=np.full((3,2),"Spurs")

In [23]:
print(spurs)

[['Spurs' 'Spurs']
 ['Spurs' 'Spurs']
 ['Spurs' 'Spurs']]


# full Like

In [98]:
np.full_like(b,6) #same shape as an arrray we already used

array([[6, 6, 6],
       [6, 6, 6]])

# identity matrix

In [35]:
np.identity(5) #takes only one parameter

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
identity_matrix=5*np.identity(5)

In [6]:
identity_matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

# eye
The numpy.eye() function in Python's NumPy library is used to create a 2-dimensional array (matrix) with ones on a specified diagonal and zeros elsewhere. This function is commonly used to generate identity matrices, which are square matrices with ones only on the main diagonal and zeros in all other positions. 
Key parameters of numpy.eye():
N: The number of rows in the output array.
M (optional): The number of columns in the output array. If None, it defaults to N, resulting in a square matrix.
k (optional): The index of the diagonal.
k=0 (default) refers to the main diagonal.
Positive values of k refer to upper diagonals (above the main diagonal).
Negative values of k refer to lower diagonals (below the main diagonal).
dtype (optional): The data type of the returned array (e.g., int, float).
order (optional): Specifies the memory layout of the array, either 'C' (row-major) or 'F' (column-major).

In [36]:
eye=np.eye(6,5,-1,dtype='int') # K- negative goes left # K- positive goes right


In [37]:
eye


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [38]:
eye=np.eye(5,5,2)

In [39]:
eye

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# arrange

In [40]:
arange= np.arange(7) #starts from index 0

In [41]:
arange

array([0, 1, 2, 3, 4, 5, 6])

In [42]:
arange=np.arange(2,20,4) #arrange(starting value,ending  vlaue, step size(interval between them)) 

In [43]:
arange

array([ 2,  6, 10, 14, 18])

# linspace 

In [54]:
linspace = np.linspace (2,20,4) #Linspace (start point, end point, number of values) 

In [55]:
linspace

array([ 2.,  8., 14., 20.])

In [46]:
linspace. size #default=50

50

In [47]:
linspace = np.linspace (50,100,5, dtype='int')

In [48]:
linspace

array([ 50,  62,  75,  87, 100])

# empty
numpy.empty(shape, dtype=float, order='C')


An "empty" NumPy array refers to an array that has been allocated memory but whose elements have not been initialized to any specific value, such as zero. Instead, the elements contain whatever arbitrary data happened to be in those memory locations when the array was created. This can offer a performance advantage over initializing all elements, especially for very large arrays, if the subsequent code will immediately overwrite all the elements anyway.

In [49]:
empty =np.empty((7,4))

In [50]:
empty #returns memory location 

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307],
       [1.02360935e-306, 1.69120416e-306, 1.78022342e-306,
        6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.42419530e-306],
       [1.11261027e-306, 9.79097007e-307, 1.78019354e-306,
        6.89810244e-307],
       [9.34609111e-307, 1.42419530e-306, 2.22522596e-306,
        6.95260585e-310]])

# random number

### int

In [29]:
arr1 = np.random.randint(1,10,size=4) #1D Array

In [30]:
arr1

array([8, 1, 5, 3], dtype=int32)

In [53]:
arr2 = np.random.randint(1,10,size=(3,3)) #2D array

In [54]:
arr2

array([[8, 6, 6],
       [8, 2, 3],
       [8, 1, 5]], dtype=int32)

In [31]:
arr3 = np.random.randint(1,10,(3,3)) #range,size

In [33]:
print(arr3)

[[3 7 1]
 [8 2 3]
 [2 1 5]]


### float

### 3D

In [44]:
arr3=np.random.rand(3,2,3) #3D,Row,Column

In [45]:
arr3

array([[[0.27574381, 0.71707563, 0.08009198],
        [0.80583703, 0.64327732, 0.79050993]],

       [[0.54314068, 0.52945921, 0.66912727],
        [0.95186379, 0.5805173 , 0.33741716]],

       [[0.80725752, 0.88395224, 0.96618261],
        [0.29912595, 0.47539711, 0.09977979]]])

### 2D

In [16]:
random_numbers = np.random.rand(7, 5)

In [13]:
print(random_numbers)

[[0.18141748 0.23802723 0.9274227  0.55284483 0.62608475]
 [0.06693156 0.19282968 0.86207788 0.45094844 0.43946198]
 [0.29485815 0.72566119 0.75771856 0.73876317 0.42683936]
 [0.99647288 0.27094279 0.95675007 0.12350759 0.83035609]
 [0.95259387 0.02795366 0.46042177 0.92740611 0.86624285]
 [0.29945158 0.92277277 0.64709348 0.17358859 0.97023922]
 [0.11569297 0.22237629 0.89890862 0.45628655 0.99395078]]


### random sample

In [26]:
arr1

array([10, 20, 30])

In [27]:
rans=np.random.random_sample(arr1.shape) #will be using same shape as arr1

In [28]:
rans

array([0.13595644, 0.42732275, 0.71225396])

# array indexing

### 1D Array (Vector)

In [55]:
import numpy as np
arr3 = np.array([1, 2, 3, 4, 6])
print(arr3[0])


1


In [56]:
print(arr3[-1])


6


### 2D Array (Matrix)

In [57]:
arr4=np.array([[1,2,3],[4,5,6]])

In [58]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
print(arr4[1,2]) # [Row,Column]

6


In [60]:
arr5=np.random.randint(1,48,size=(5,5))

In [61]:
print(arr5)

[[41 39  3 41 13]
 [34 16 14 39  2]
 [31 30 21 40 24]
 [33 20 45 21 38]
 [40 15 20 13 23]]


In [62]:
#print 46 from the above
print(arr5[1,2])

14


### 3D Array

In [63]:
arr6=np.random.randint(1,47,size=(3,4,3))

In [64]:
print(arr6)

[[[42 25 40]
  [12 34 30]
  [16 19 27]
  [21 33 39]]

 [[42 30 10]
  [ 1 27 22]
  [41 24 19]
  [19 29 44]]

 [[27 46  1]
  [ 6 29 15]
  [14 23  3]
  [33 36 24]]]


In [65]:
print(arr6[2,2,1]) #[Set,Row,Column]

23


### Get all rows

In [66]:
arr5[0,:]

array([41, 39,  3, 41, 13], dtype=int32)

In [67]:
arr6[:,0,:]

array([[42, 25, 40],
       [42, 30, 10],
       [27, 46,  1]], dtype=int32)

### Get all columns

In [68]:
arr5[:,0]

array([41, 34, 31, 33, 40], dtype=int32)

In [69]:
arr6[:,:,0]

array([[42, 12, 16, 21],
       [42,  1, 41, 19],
       [27,  6, 14, 33]], dtype=int32)

### iteration

In [70]:
array_indx=np.array([[1,3,5,7,9,11],[2,4,6,8,10,12]])

In [71]:
array_indx

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [72]:
array_indx[1,0:-2:2]

array([2, 6])

### Replace

In [92]:
replace=np.random.randint(10,100,size=(3,2,3))

In [93]:
replace

array([[[82, 88, 98],
        [83, 76, 44]],

       [[68, 81, 84],
        [75, 43, 11]],

       [[87, 98, 49],
        [43, 58, 76]]], dtype=int32)

In [94]:
replace[2,0,:]=[0,1,2]

In [95]:
replace

array([[[82, 88, 98],
        [83, 76, 44]],

       [[68, 81, 84],
        [75, 43, 11]],

       [[ 0,  1,  2],
        [43, 58, 76]]], dtype=int32)

# Copy {arrayname.copy()}

In [127]:
arr_a =np.array([1,2,3])

In [128]:
arr_a

array([1, 2, 3])

In [129]:
arr_b=arr_a

In [131]:
arr_b

array([1, 2, 3])

In [132]:
arr_b= arr_a

In [133]:
arr_b[0]=100

In [134]:
arr_b

array([100,   2,   3])

In [135]:
arr_a #value of a is also changed. That is why we should use copy()

array([100,   2,   3])

In [137]:
arr_c=np.array([4,5,6])

In [138]:
arr_c

array([4, 5, 6])

In [139]:
arr_d=arr_c.copy()

In [140]:
arr_d 

array([4, 5, 6])

In [141]:
arr_d[0]=10

In [142]:
arr_d

array([10,  5,  6])

In [143]:
arr_c

array([4, 5, 6])

# Array Slicing

In [ ]:
# Slicing in Python (and NumPy) includes the start index but excludes the end index 

In [77]:
pizza1=np.random.randint(10,20,5)
pizza2=np.random.randint(1,20,size=(2,3))

In [78]:
print(pizza1)

[10 14 10 13 18]


In [79]:
print(pizza2)

[[14 19  1]
 [12  4  6]]


In [81]:
print(pizza1[1:3])

[14 10]


In [122]:
orders=np.array(['cheese','veg','spicy','bbq'])

In [124]:
print(orders)

['cheese' 'veg' 'spicy' 'bbq']


In [126]:
print(orders[1:3])

['veg' 'spicy']


### 2D Array

In [158]:
pizza2=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [159]:
print(pizza2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [170]:
print(pizza2[:,1]) #row all #column 1

[2 5 8]


In [172]:
print(pizza2[1,:]) #row 0 column all

[4 5 6]


In [173]:
print(pizza2 [0:2,0:1]) #first two row and first column


[[1]
 [4]]


In [161]:
print(pizza2 [1:])  # row2 to all

[[4 5 6]
 [7 8 9]]


In [162]:
print(pizza2 [:1])  

[[1 2 3]]


In [168]:
print(pizza2 [2:]) 

[[7 8 9]]


In [177]:
print(pizza2 [:2]) 

[[1 2 3]
 [4 5 6]]


In [174]:
print(pizza2 [1:,1:])

[[5 6]
 [8 9]]


In [182]:
print(pizza2 [:2,1:])

[[2 3]
 [5 6]]


In [183]:
print(pizza2 [:2,:1])

[[1]
 [4]]


In [184]:
print(pizza2 [:2,1:3])

[[2 3]
 [5 6]]


In [164]:
orders2=np.array([['cheese','veg'],['spicy','bbq']])

In [165]:
print(orders2)

[['cheese' 'veg']
 ['spicy' 'bbq']]


In [166]:
print(orders2[0,1]) # Row 0 , Column 1

veg


### 3D array

In [137]:
pizza3=np.array([[[1,2,3],
          [4,5,6],
          [7,8,9]]])

In [138]:
pizza3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [139]:
pizza3.ndim

3

In [144]:
print(pizza3[0,1,2]) #index,row,column

6


In [ ]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])


In [ ]:
arr

In [ ]:
arr[1:3]

In [ ]:
arr[1:3,1:3]

In [ ]:
arr[1:3,1:3]=0

In [ ]:
arr

# reshape

In [ ]:
array=np.random.randint(5,20,size=(2,3))

In [ ]:
print(array)

In [ ]:
#method 1
print(np.reshape(array,(3,2))) #np.reshape(name of the array, (new shape (row,column))

In [ ]:
#method 2 
print(array.reshape(3,2)) #arrayname.reshape((new shape (row,column))

# resize 

In [ ]:
array1= np.random.randint(1,15,size=(3,3))


In [ ]:
print(array1)

In [ ]:
print(np.resize(array1,(5,3))) #method 1

In [ ]:
array1.resize(6,3) #method 2

In [ ]:
print(array1)

# ravel()

In [ ]:
arr10=np.array([[2,3,4],[12,13,14]])

In [ ]:
arr10

In [ ]:
print(arr10.ravel())



In [ ]:
ravel= arr10.ravel()

In [ ]:
ravel.shape

# flatten()
flatten(): Always returns a copy of the original array. Modifications to the flattened array will not affect the original array.

In [ ]:
arr11=np.array([[10,20,30],[40,50,60]])

In [ ]:
arr11

In [ ]:
arr11.flatten()

In [ ]:
arr12=np.array([[4,5,6],[7,8,9]])

In [ ]:
arr12

In [ ]:
ravel=arr12.ravel()

In [ ]:
ravel

In [ ]:
flatten=arr12.flatten()

In [ ]:
flatten

In [ ]:
flatten[0]=40

In [ ]:
flatten

In [ ]:
arr12

In [ ]:
ravel

In [ ]:
ravel[0]=40

In [ ]:
arr12

# repeat

In [106]:
rep=np.array([1,2,3])

In [107]:
np.repeat(rep,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [110]:
np.repeat(rep,3,axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [112]:
rep2=np.array([[1,2,3],[4,5,6]])

In [113]:
rep2

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
np.repeat(rep2,3,axis=0) #rows

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [122]:
np.repeat(rep2,3,axis=1) #columns

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

# Stacking

### hstack(), column_stack()

In [ ]:
a=np.random.randint(1,10,size=(3,3))

In [ ]:
print(a)

In [ ]:
b=a*2

In [ ]:
print(b)

In [ ]:
print(np.hstack((a,b)))

In [ ]:
print(np.column_stack((a,b)))

### vstack(),row_stack()

In [ ]:
a=np.random.randint(1,10,size=(3,3))

In [ ]:
print(a)

In [ ]:
b=a*2

In [ ]:
print(b)

In [ ]:
vstack= np.vstack((a,b))

In [ ]:
print(vstack)

In [ ]:
#rowstack=np.row_stack((a,b))

In [ ]:
#print(rowstack)

### concatenate()

In [ ]:
np.concatenate((a,b),axis=0) #effects row

In [ ]:
np.concatenate((a,b),axis=1) #effects column

### dstack( )

In [ ]:
x= np.random.randint(1,10,size=(2,3))

In [ ]:
x

In [ ]:
y= np.random.randint(10,20,size=(2,3))

In [ ]:
y

In [ ]:
np.dstack((x,y))

# argmax,argmin

In [199]:
num=np.array([40,20,10,30,50])

In [200]:
print(np.argmax(num)) #index

4


In [201]:
print(np.argmin(num)) #index

2


### max

In [197]:
print(np.max(num)) #index

50


### min

In [193]:
print(np.min(num)) #index

10
