# Import Numpy

In [29]:
import numpy as np


# 1D array

In [30]:
a= np.array(([1,2,3]))

In [31]:
a

array([1, 2, 3])

# shape
(rows, columns)

In [32]:
a.shape #shows info about row and column

(3,)

# dimension

In [33]:
a.ndim #returns the dimsnion of the array

1

# 2D array

In [34]:
b= np.array(
    [[2,3,4], [4,5,6]] #double bracket symbllizes 2D
)

In [35]:
b

array([[2, 3, 4],
       [4, 5, 6]])

In [36]:
b.shape


(2, 3)

In [37]:
b.ndim

2

# 3D Array

In [38]:
c=np.array([[[1,2,3],
          [4,5,6]]])

In [39]:
c

array([[[1, 2, 3],
        [4, 5, 6]]])

In [40]:
c.shape

(1, 2, 3)

In [41]:
c.ndim

3

# Data Type

In [42]:
a.dtype,b.dtype,c.dtype #dtype shows us the data type of the given array

(dtype('int64'), dtype('int64'), dtype('int64'))

In [48]:
d1=np.array(([1,2,3]))#1D
d2=np.array(([[1,2,3]]))#2D
d3=np.array(([[[1,2,3]]]))#3D


In [52]:
d=d1,d2,d3

In [53]:
d

(array([1, 2, 3]), array([[1, 2, 3]]), array([[[1, 2, 3]]]))

In [56]:
f=np.array(([1.5,2.4,3.2]))

In [57]:
f

array([1.5, 2.4, 3.2])

In [59]:
f.dtype #float type

dtype('float64')

# Elements

In [63]:
c=np.array([[[1,2,3],
          [4,5,6]]])

In [65]:
c.size #how many elements are there in the array (rows + columns)

6

# Memory Allocation

In [67]:
c.nbytes #how many bytes consumed by array

48

# Array Creation

In [68]:
arr=np.array([4,5,6],dtype='int' )

In [69]:
arr

array([4, 5, 6])

# zeros

In [70]:
zeros=np.zeros((2,2),dtype='int')  

In [71]:
zeros

array([[0, 0],
       [0, 0]])

In [72]:
zeros=np.zeros((3,2),dtype='float')  

In [73]:
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# ones

In [81]:
ones=np.ones((3,2))  #dtype default float

In [82]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# full

In [80]:
np.full ((2,3),5) # np.full((shape), element)

array([[5, 5, 5],
       [5, 5, 5]])

# identity matrix

In [84]:
np.identity(5) #takes only one parameter

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# eye
The numpy.eye() function in Python's NumPy library is used to create a 2-dimensional array (matrix) with ones on a specified diagonal and zeros elsewhere. This function is commonly used to generate identity matrices, which are square matrices with ones only on the main diagonal and zeros in all other positions. 
Key parameters of numpy.eye():
N: The number of rows in the output array.
M (optional): The number of columns in the output array. If None, it defaults to N, resulting in a square matrix.
k (optional): The index of the diagonal.
k=0 (default) refers to the main diagonal.
Positive values of k refer to upper diagonals (above the main diagonal).
Negative values of k refer to lower diagonals (below the main diagonal).
dtype (optional): The data type of the returned array (e.g., int, float).
order (optional): Specifies the memory layout of the array, either 'C' (row-major) or 'F' (column-major).

In [111]:
eye=np.eye(6,5,-1,dtype='int') # K- negative goes left # K- positive goes right


In [112]:
eye


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [109]:
eye=np.eye(5,5,2)

In [110]:
eye

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# arrange

In [120]:
arange= np.arange(7) #starts from index 0

In [121]:
arange

array([0, 1, 2, 3, 4, 5, 6])

In [122]:
arange=np.arange(2,20,4) #arrange(starting value,ending  vlaue, step size)

In [123]:
arange

array([ 2,  6, 10, 14, 18])

# linspace 

In [132]:
linspace = np.linspace (1,100) #Linspace (start point, end point, number of values) 

In [133]:
linspace

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [136]:
linspace. size #default=50

50

In [139]:
linspace = np.linspace (50,100,5, dtype='int')

In [140]:
linspace

array([ 50,  62,  75,  87, 100])

# empty
numpy.empty(shape, dtype=float, order='C')


An "empty" NumPy array refers to an array that has been allocated memory but whose elements have not been initialized to any specific value, such as zero. Instead, the elements contain whatever arbitrary data happened to be in those memory locations when the array was created. This can offer a performance advantage over initializing all elements, especially for very large arrays, if the subsequent code will immediately overwrite all the elements anyway.

In [175]:
empty =np.empty((7,4))

In [178]:
empty #returns memory location 

array([[4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000],
       [4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000],
       [4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000],
       [4.00000000e+000, 4.00000000e+000, 4.00000000e+000,
        4.00000000e+000],
       [8.37404147e+242, 4.31999013e-096, 4.82337723e+228,
        1.79175794e+160],
       [1.25585767e-075, 4.96806950e-091, 1.25822946e-075,
        1.11575915e-046],
       [5.04621343e+180, 1.94918963e-153, 1.14484251e+243,
        2.59903827e-144]])