# Import Numpy

In [1]:
import numpy as np


# 1D array

In [2]:
a= np.array(([1,2,3]))

In [3]:
a

array([1, 2, 3])

# shape
(rows, columns)

In [4]:
a.shape #shows info about row and column

(3,)

# dimension

In [5]:
a.ndim #returns the dimsnion of the array

1

# 2D array

In [6]:
b= np.array(
    [[2,3,4], [4,5,6]] #double bracket symbllizes 2D
)

In [7]:
b

array([[2, 3, 4],
       [4, 5, 6]])

In [8]:
b.shape


(2, 3)

In [9]:
b.ndim

2

# 3D Array

In [10]:
c=np.array([[[1,2,3],
          [4,5,6]]])

In [11]:
c

array([[[1, 2, 3],
        [4, 5, 6]]])

In [12]:
c.shape

(1, 2, 3)

In [13]:
c.ndim

3

# Data Type

In [14]:
a.dtype,b.dtype,c.dtype #dtype shows us the data type of the given array

(dtype('int64'), dtype('int64'), dtype('int64'))

In [15]:
d1=np.array(([1,2,3]))#1D
d2=np.array(([[1,2,3]]))#2D
d3=np.array(([[[1,2,3]]]))#3D


In [16]:
d=d1,d2,d3

In [17]:
d

(array([1, 2, 3]), array([[1, 2, 3]]), array([[[1, 2, 3]]]))

In [18]:
f=np.array(([1.5,2.4,3.2]))

In [19]:
f

array([1.5, 2.4, 3.2])

In [20]:
f.dtype #float type

dtype('float64')

# Elements

In [134]:
c=np.array([[[1,2,3],
          [4,5,6]]])

### size

In [135]:
c.size #how many elements are there in the array (rows + columns)

6

### item size

In [136]:
c.itemsize #how many bytes they consume

8

### total size

In [139]:
c.nbytes # (size + item size)

48

# Memory Allocation

In [24]:
c.nbytes #how many bytes consumed by array

48

# Array Creation

In [25]:
arr=np.array([4,5,6],dtype='int' )

In [26]:
arr

array([4, 5, 6])

# zeros

In [27]:
zeros=np.zeros((2,2),dtype='int')  

In [28]:
zeros

array([[0, 0],
       [0, 0]])

In [29]:
zeros=np.zeros((3,2),dtype='float')  

In [30]:
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# ones

In [31]:
ones=np.ones((3,2))  #dtype default float

In [32]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# full

In [33]:
np.full ((2,3),5) # np.full((shape), element)

array([[5, 5, 5],
       [5, 5, 5]])

# identity matrix

In [34]:
np.identity(5) #takes only one parameter

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# eye
The numpy.eye() function in Python's NumPy library is used to create a 2-dimensional array (matrix) with ones on a specified diagonal and zeros elsewhere. This function is commonly used to generate identity matrices, which are square matrices with ones only on the main diagonal and zeros in all other positions. 
Key parameters of numpy.eye():
N: The number of rows in the output array.
M (optional): The number of columns in the output array. If None, it defaults to N, resulting in a square matrix.
k (optional): The index of the diagonal.
k=0 (default) refers to the main diagonal.
Positive values of k refer to upper diagonals (above the main diagonal).
Negative values of k refer to lower diagonals (below the main diagonal).
dtype (optional): The data type of the returned array (e.g., int, float).
order (optional): Specifies the memory layout of the array, either 'C' (row-major) or 'F' (column-major).

In [35]:
eye=np.eye(6,5,-1,dtype='int') # K- negative goes left # K- positive goes right


In [36]:
eye


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [37]:
eye=np.eye(5,5,2)

In [38]:
eye

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# arrange

In [39]:
arange= np.arange(7) #starts from index 0

In [40]:
arange

array([0, 1, 2, 3, 4, 5, 6])

In [41]:
arange=np.arange(2,20,4) #arrange(starting value,ending  vlaue, step size)

In [42]:
arange

array([ 2,  6, 10, 14, 18])

# linspace 

In [43]:
linspace = np.linspace (1,100) #Linspace (start point, end point, number of values) 

In [44]:
linspace

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [45]:
linspace. size #default=50

50

In [46]:
linspace = np.linspace (50,100,5, dtype='int')

In [47]:
linspace

array([ 50,  62,  75,  87, 100])

# empty
numpy.empty(shape, dtype=float, order='C')


An "empty" NumPy array refers to an array that has been allocated memory but whose elements have not been initialized to any specific value, such as zero. Instead, the elements contain whatever arbitrary data happened to be in those memory locations when the array was created. This can offer a performance advantage over initializing all elements, especially for very large arrays, if the subsequent code will immediately overwrite all the elements anyway.

In [48]:
empty =np.empty((7,4))

In [49]:
empty #returns memory location 

array([[ 4.35678737e-313,  4.32887141e-312,  1.08858384e-311,
         6.79453105e-313],
       [ 5.45352919e-312,  3.82373695e-313,  1.48590217e-313,
         2.78166063e-309],
       [ 7.29112202e-304,  2.78134232e-308,  5.45352983e-312,
         2.55053947e-313],
       [ 2.08603857e-308,  1.34497462e-284,  1.15436571e-311,
        -2.68156159e+154],
       [ 7.29112202e-304,  2.78731786e-308,  5.47209665e-312,
         2.55053947e-313],
       [ 1.28822975e-231,  1.34497462e-284,  1.15436571e-311,
         1.28822975e-231],
       [ 3.13151306e-294,  3.89388350e-308,  2.78137840e-308,
         5.45352918e-312]])

# random number

In [50]:
arr1 = np.random.randint(1,10,size=4) #1D Array

In [51]:
arr1

array([5, 2, 6, 3], dtype=int32)

In [52]:
arr2 = np.random.randint(1,10,size=(3,3)) #2D array

In [53]:
arr2

array([[8, 4, 6],
       [9, 8, 1],
       [8, 7, 7]], dtype=int32)

# array indexing

### 1D Array (Vector)

In [54]:
import numpy as np
arr3 = np.array([1, 2, 3, 4, 6])
print(arr3[0])


1


In [55]:
print(arr3[-1])


6


### 2D Array (Matrix)

In [56]:
arr4=np.array([[1,2,3],[4,5,6]])

In [57]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
print(arr4[1,2]) # [Row,Column]

6


In [59]:
arr5=np.random.randint(1,48,size=(5,5))

In [60]:
print(arr5)

[[19  6 15 37 11]
 [ 4 15 41 17  6]
 [46 45 32 39 15]
 [26 26 18 27 39]
 [20 25 38 47 12]]


In [61]:
#print 46 from the above
print(arr5[1,2])

41


### 3D Array

In [62]:
arr6=np.random.randint(1,47,size=(3,4,3))

In [63]:
print(arr6)

[[[18 26 38]
  [12 34 39]
  [10 25 23]
  [34 10 39]]

 [[39 40 11]
  [19  1 43]
  [37 38 39]
  [35 33 12]]

 [[42 35 20]
  [36 46  8]
  [20 14 35]
  [20 17 26]]]


In [64]:
print(arr6[2,2,1]) #[Set,Row,Column]

14


# Array Slicing

In [65]:
# Slicing in Python (and NumPy) includes the start index but excludes the end index 

### 1D Array

In [66]:
arr3

array([1, 2, 3, 4, 6])

In [67]:
arr3[1:3] #print 2,3

array([2, 3])

In [68]:
arr3[1:] #print 2,3,4,6

array([2, 3, 4, 6])

### 2D Array

In [69]:
arr6=np.random.randint(5,10,size=(3,3))

In [70]:
print(arr6)

[[6 7 5]
 [5 9 7]
 [9 8 6]]


In [71]:
print(arr6[0:2])

[[6 7 5]
 [5 9 7]]


In [72]:
print(arr6 [0:2,0:2]) #first two row and column


[[6 7]
 [5 9]]


In [73]:
print(arr6 [1:])

[[5 9 7]
 [9 8 6]]


In [74]:
print(arr6 [1:,1:])

[[9 7]
 [8 6]]


In [75]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])


In [76]:
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [77]:
arr[1:3]

array([[ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [78]:
arr[1:3,1:3]

array([[ 60,  70],
       [100, 110]])

In [79]:
arr[1:3,1:3]=0

In [80]:
arr

array([[ 10,  20,  30,  40],
       [ 50,   0,   0,  80],
       [ 90,   0,   0, 120],
       [130, 140, 150, 160]])

# reshape

In [81]:
array=np.random.randint(5,20,size=(2,3))

In [82]:
print(array)

[[17  5 15]
 [19 13 12]]


In [83]:
#method 1
print(np.reshape(array,(3,2))) #np.reshape(name of the array, (new shape (row,column))

[[17  5]
 [15 19]
 [13 12]]


In [84]:
#method 2 
print(array.reshape(3,2)) #arrayname.reshape((new shape (row,column))

[[17  5]
 [15 19]
 [13 12]]


# resize 

In [85]:
array1= np.random.randint(1,15,size=(3,3))


In [86]:
print(array1)

[[ 2 13 11]
 [ 9  9 11]
 [11  6  7]]


In [87]:
print(np.resize(array1,(5,3))) #method 1

[[ 2 13 11]
 [ 9  9 11]
 [11  6  7]
 [ 2 13 11]
 [ 9  9 11]]


In [88]:
array1.resize(6,3) #method 2

In [89]:
print(array1)

[[ 2 13 11]
 [ 9  9 11]
 [11  6  7]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]]


# ravel()

In [90]:
arr10=np.array([[2,3,4],[12,13,14]])

In [91]:
arr10

array([[ 2,  3,  4],
       [12, 13, 14]])

In [92]:
print(arr10.ravel())



[ 2  3  4 12 13 14]


In [93]:
ravel= arr10.ravel()

In [94]:
ravel.shape

(6,)

# flatten()
flatten(): Always returns a copy of the original array. Modifications to the flattened array will not affect the original array.

In [95]:
arr11=np.array([[10,20,30],[40,50,60]])

In [96]:
arr11

array([[10, 20, 30],
       [40, 50, 60]])

In [97]:
arr11.flatten()

array([10, 20, 30, 40, 50, 60])

In [98]:
arr12=np.array([[4,5,6],[7,8,9]])

In [99]:
arr12

array([[4, 5, 6],
       [7, 8, 9]])

In [100]:
ravel=arr12.ravel()

In [101]:
ravel

array([4, 5, 6, 7, 8, 9])

In [102]:
flatten=arr12.flatten()

In [103]:
flatten

array([4, 5, 6, 7, 8, 9])

In [104]:
flatten[0]=40

In [105]:
flatten

array([40,  5,  6,  7,  8,  9])

In [106]:
arr12

array([[4, 5, 6],
       [7, 8, 9]])

In [107]:
ravel

array([4, 5, 6, 7, 8, 9])

In [108]:
ravel[0]=40

In [109]:
arr12

array([[40,  5,  6],
       [ 7,  8,  9]])

# Stacking

### hstack(), column_stack()

In [110]:
a=np.random.randint(1,10,size=(3,3))

In [111]:
print(a)

[[1 3 3]
 [6 6 1]
 [6 2 2]]


In [112]:
b=a*2

In [113]:
print(b)

[[ 2  6  6]
 [12 12  2]
 [12  4  4]]


In [114]:
print(np.hstack((a,b)))

[[ 1  3  3  2  6  6]
 [ 6  6  1 12 12  2]
 [ 6  2  2 12  4  4]]


In [115]:
print(np.column_stack((a,b)))

[[ 1  3  3  2  6  6]
 [ 6  6  1 12 12  2]
 [ 6  2  2 12  4  4]]


### vstack(),row_stack()

In [116]:
a=np.random.randint(1,10,size=(3,3))

In [117]:
print(a)

[[1 2 5]
 [2 2 7]
 [7 7 5]]


In [118]:
b=a*2

In [119]:
print(b)

[[ 2  4 10]
 [ 4  4 14]
 [14 14 10]]


In [120]:
vstack= np.vstack((a,b))

In [121]:
print(vstack)

[[ 1  2  5]
 [ 2  2  7]
 [ 7  7  5]
 [ 2  4 10]
 [ 4  4 14]
 [14 14 10]]


In [122]:
#rowstack=np.row_stack((a,b))

In [123]:
#print(rowstack)

### concatenate()

In [124]:
np.concatenate((a,b),axis=0) #effects row

array([[ 1,  2,  5],
       [ 2,  2,  7],
       [ 7,  7,  5],
       [ 2,  4, 10],
       [ 4,  4, 14],
       [14, 14, 10]], dtype=int32)

In [125]:
np.concatenate((a,b),axis=1) #effects column

array([[ 1,  2,  5,  2,  4, 10],
       [ 2,  2,  7,  4,  4, 14],
       [ 7,  7,  5, 14, 14, 10]], dtype=int32)

### dstack( )

In [126]:
x= np.random.randint(1,10,size=(2,3))

In [127]:
x

array([[6, 1, 5],
       [8, 3, 3]], dtype=int32)

In [128]:
y= np.random.randint(10,20,size=(2,3))

In [129]:
y

array([[19, 17, 12],
       [11, 15, 18]], dtype=int32)

In [130]:
np.dstack((x,y))

array([[[ 6, 19],
        [ 1, 17],
        [ 5, 12]],

       [[ 8, 11],
        [ 3, 15],
        [ 3, 18]]], dtype=int32)