# Import Numpy

In [1]:
import numpy as np


# 1D array /Vector

In [2]:
a= np.array(([1,2,3]))

In [3]:
a

array([1, 2, 3])

# shape
(rows, columns)

In [4]:
a.shape #shows info about row and column

(3,)

# dimension

In [5]:
a.ndim #returns the dimsnion of the array

1

# 2D array /Matrix

In [6]:
b= np.array(
    [[2,3,4], [4,5,6]] #double bracket symbllizes 2D
)

In [7]:
b

array([[2, 3, 4],
       [4, 5, 6]])

In [8]:
b.shape


(2, 3)

In [9]:
b.ndim

2

# 3D Array /Tensor

In [10]:
c=np.array([[[1,2,3],
          [4,5,6]]])

In [11]:
c

array([[[1, 2, 3],
        [4, 5, 6]]])

In [12]:
c.shape

(1, 2, 3)

In [13]:
c.ndim

3

# Data Type

In [14]:
a.dtype,b.dtype,c.dtype #dtype shows us the data type of the given array

(dtype('int64'), dtype('int64'), dtype('int64'))

In [15]:
d1=np.array(([1,2,3]))#1D
d2=np.array(([[1,2,3]]))#2D
d3=np.array(([[[1,2,3]]]))#3D


In [16]:
d=d1,d2,d3

In [17]:
d

(array([1, 2, 3]), array([[1, 2, 3]]), array([[[1, 2, 3]]]))

In [18]:
f=np.array(([1.5,2.4,3.2]))

In [19]:
f

array([1.5, 2.4, 3.2])

In [20]:
f.dtype #float type

dtype('float64')

# Elements

In [21]:
c=np.array([[[1,2,3],
          [4,5,6]]])

### size

In [22]:
c.size #how many elements are there in the array (rows + columns)

6

### item size

In [23]:
c.itemsize #how many bytes they consume

8

### total size

In [24]:
c.nbytes # (size * item size)

48

# Memory Allocation

In [25]:
c.nbytes #how many bytes consumed by array

48

# Array Creation

In [26]:
arr=np.array([4,5,6],dtype='int' )

In [27]:
arr

array([4, 5, 6])

# Array Sum

In [28]:
list1=[1,2,3]
list2=[4,5,6]

print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [29]:
arr1=np.array([10,20,30])
arr2=np.array([4,5,6])
print(arr1+arr2)


[14 25 36]


array* 40%

In [30]:
arr1*0.4

array([ 4.,  8., 12.])

In [250]:
arr= np.arange(0,25).reshape(5,5)

In [251]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [252]:
arr.sum(axis=0)  #row

array([50, 55, 60, 65, 70])

In [253]:
arr.sum(axis=1) #column

array([ 10,  35,  60,  85, 110])

# zeros

In [31]:
zeros=np.zeros((2,2),dtype='int')  

In [32]:
zeros

array([[0, 0],
       [0, 0]])

In [33]:
zeros=np.zeros((3,2),dtype='float')  

In [34]:
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# ones

In [35]:
ones=np.ones((3,2))  #dtype default float

In [36]:
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

# full

In [37]:
np.full ((2,3),5) # np.full((shape), element)

array([[5, 5, 5],
       [5, 5, 5]])

In [38]:
np.full (5,10.0) #iteration, value

array([10., 10., 10., 10., 10.])

### Value of your own

In [39]:
spurs=np.full((3,2),"Spurs")

In [40]:
print(spurs)

[['Spurs' 'Spurs']
 ['Spurs' 'Spurs']
 ['Spurs' 'Spurs']]


# full Like

In [41]:
np.full_like(b,6) #same shape as an arrray we already used

array([[6, 6, 6],
       [6, 6, 6]])

# identity matrix

In [42]:
np.identity(5) #takes only one parameter

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
identity_matrix=5*np.identity(5)

In [44]:
identity_matrix

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

# eye
The numpy.eye() function in Python's NumPy library is used to create a 2-dimensional array (matrix) with ones on a specified diagonal and zeros elsewhere. This function is commonly used to generate identity matrices, which are square matrices with ones only on the main diagonal and zeros in all other positions. 


In [45]:
eye=np.eye(6,5,-1,dtype='int') # K- negative goes left # K- positive goes right


In [46]:
eye


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [47]:
eye=np.eye(5,5,2)

In [48]:
eye

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [49]:
eye=np.eye(5)*5

In [50]:
eye

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

# arange

In [51]:
arange= np.arange(7) #starts from index 0

In [52]:
arange

array([0, 1, 2, 3, 4, 5, 6])

In [53]:
arange=np.arange(2,20,4) #arrange(starting value,ending  vlaue, step size(interval between them)) 

In [54]:
arange

array([ 2,  6, 10, 14, 18])

# linspace 

In [55]:
linspace = np.linspace (2,20,4) #Linspace (start point, end point, number of values) 

In [56]:
linspace

array([ 2.,  8., 14., 20.])

In [57]:
linspace. size #default=50

4

In [58]:
linspace = np.linspace (50,100,5, dtype='int')

In [59]:
linspace

array([ 50,  62,  75,  87, 100])

# empty
numpy.empty(shape, dtype=float, order='C')


An "empty" NumPy array refers to an array that has been allocated memory but whose elements have not been initialized to any specific value, such as zero. Instead, the elements contain whatever arbitrary data happened to be in those memory locations when the array was created. This can offer a performance advantage over initializing all elements, especially for very large arrays, if the subsequent code will immediately overwrite all the elements anyway.

In [60]:
empty =np.empty((7,4))

In [61]:
empty #returns memory location 

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307],
       [1.02360935e-306, 1.69120416e-306, 1.78022342e-306,
        6.23058028e-307],
       [1.06811422e-306, 9.45699680e-308, 1.11258854e-306,
        1.11261502e-306],
       [1.42410839e-306, 7.56597770e-307, 6.23059726e-307,
        1.42419530e-306],
       [1.11261027e-306, 9.79097007e-307, 1.78019354e-306,
        6.89810244e-307],
       [9.34609111e-307, 1.42419530e-306, 2.22522596e-306,
        1.42410974e-306]])

# random number

### int

In [62]:
arr1 = np.random.randint(1,10,size=4) #1D Array

In [63]:
arr1

array([1, 4, 2, 8], dtype=int32)

In [64]:
arr2 = np.random.randint(1,10,size=(3,3)) #2D array

In [65]:
arr2

array([[7, 7, 1],
       [3, 3, 1],
       [3, 6, 2]], dtype=int32)

In [66]:
arr3 = np.random.randint(1,10,(3,3)) #range,size

In [67]:
print(arr3)

[[4 1 3]
 [3 3 3]
 [6 6 5]]


### float

### 3D

In [68]:
arr3=np.random.rand(3,2,3) #3D,Row,Column

In [69]:
arr3

array([[[0.20587608, 0.86209924, 0.05128157],
        [0.38544934, 0.27619704, 0.79556685]],

       [[0.18975347, 0.19222226, 0.98066962],
        [0.50432063, 0.69596673, 0.49514634]],

       [[0.23083288, 0.8166813 , 0.49678292],
        [0.72548978, 0.04742821, 0.78000449]]])

### 2D

In [70]:
random_numbers = np.random.rand(7, 5)

In [71]:
print(random_numbers)

[[0.73328302 0.5172017  0.10055231 0.59097575 0.11804411]
 [0.56461245 0.99684786 0.66699842 0.64593076 0.7955269 ]
 [0.47969354 0.88880724 0.51793245 0.96364078 0.36954681]
 [0.58527209 0.53024682 0.14708314 0.18020886 0.56955477]
 [0.32619975 0.95410004 0.80889137 0.19139851 0.9120147 ]
 [0.97882458 0.38187758 0.6374432  0.46364636 0.36707564]
 [0.31052578 0.742282   0.03425804 0.24871244 0.10810715]]


### random sample

In [72]:
arr1

array([1, 4, 2, 8], dtype=int32)

In [73]:
rans=np.random.random_sample(arr1.shape) #will be using same shape as arr1

In [74]:
rans

array([0.53268938, 0.48469697, 0.85694788, 0.07692259])

### Random Fix or Reusbale Value 

In [75]:
np.random.seed(42)
np.random.randint(1,100,(2,5))

array([[52, 93, 15, 72, 61],
       [21, 83, 87, 75, 75]], dtype=int32)

### uniform Distrubtion

In [76]:
np.random.rand(5)

array([0.86617615, 0.60111501, 0.70807258, 0.02058449, 0.96990985])

In [77]:
np.random.rand(5,5)

array([[0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224],
       [0.52475643, 0.43194502, 0.29122914, 0.61185289, 0.13949386],
       [0.29214465, 0.36636184, 0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041, 0.60754485, 0.17052412],
       [0.06505159, 0.94888554, 0.96563203, 0.80839735, 0.30461377]])

# array indexing

### 1D Array (Vector)

In [78]:
import numpy as np
arr3 = np.array([1, 2, 3, 4, 6])
print(arr3[0])


1


In [79]:
print(arr3[-1])


6


### 2D Array (Matrix)

In [80]:
arr4=np.array([[1,2,3],[4,5,6]])

In [81]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
print(arr4[1,2]) # [Row,Column]

6


In [83]:
arr5=np.random.randint(1,48,size=(5,5))

In [84]:
print(arr5)

[[ 2 20 28 47  7]
 [44  8 47 35 14]
 [17 36 40  4  2]
 [ 6 42  4 29 18]
 [26 44 34 10 36]]


In [85]:
#print 46 from the above
print(arr5[1,2])

47


### 3D Array

In [86]:
arr6=np.random.randint(1,47,size=(3,4,3))

In [87]:
print(arr6)

[[[14 31 15]
  [ 8 14 23]
  [40 21 16]
  [45 18 24]]

 [[26 25 45]
  [41 29 15]
  [45  1 25]
  [ 7  9 24]]

 [[ 1 44  8]
  [24 11 17]
  [ 8 35 35]
  [33  5 42]]]


In [88]:
print(arr6[2,2,1]) #[Set,Row,Column]

35


### Get all rows

In [89]:
arr5[0,:]

array([ 2, 20, 28, 47,  7], dtype=int32)

In [90]:
arr6[:,0,:]

array([[14, 31, 15],
       [26, 25, 45],
       [ 1, 44,  8]], dtype=int32)

### Get all columns

In [91]:
arr5[:,0]

array([ 2, 44, 17,  6, 26], dtype=int32)

In [92]:
arr6[:,:,0]

array([[14,  8, 40, 45],
       [26, 41, 45,  7],
       [ 1, 24,  8, 33]], dtype=int32)

### iteration

In [93]:
array_indx=np.array([[1,3,5,7,9,11],[2,4,6,8,10,12]])

In [94]:
array_indx

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [95]:
array_indx[1,0:-2:2]

array([2, 6])

### Replace

In [96]:
replace=np.random.randint(10,100,size=(3,2,3))

In [97]:
replace

array([[[50, 37, 16],
        [82, 81, 21]],

       [[43, 42, 57],
        [32, 71, 97]],

       [[46, 53, 95],
        [44, 74, 56]]], dtype=int32)

In [98]:
replace[2,0,:]=[0,1,2]

In [99]:
replace

array([[[50, 37, 16],
        [82, 81, 21]],

       [[43, 42, 57],
        [32, 71, 97]],

       [[ 0,  1,  2],
        [44, 74, 56]]], dtype=int32)

# Copy {arrayname.copy()}

In [100]:
arr_a =np.array([1,2,3])

In [101]:
arr_a

array([1, 2, 3])

In [102]:
arr_b=arr_a

In [103]:
arr_b

array([1, 2, 3])

In [104]:
arr_b= arr_a

In [105]:
arr_b[0]=100

In [106]:
arr_b

array([100,   2,   3])

In [107]:
arr_a #value of a is also changed. That is why we should use copy()

array([100,   2,   3])

In [108]:
arr_c=np.array([4,5,6])

In [109]:
arr_c

array([4, 5, 6])

In [110]:
arr_d=arr_c.copy()

In [111]:
arr_d 

array([4, 5, 6])

In [112]:
arr_d[0]=10

In [113]:
arr_d

array([10,  5,  6])

In [114]:
arr_c

array([4, 5, 6])

# Array Broadcasting

In [238]:
arr_bradcasting=np.arange(0,10)

In [239]:
arr_bradcasting

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [240]:
arr_bradcasting[4]=20

In [241]:
arr_bradcasting

array([ 0,  1,  2,  3, 20,  5,  6,  7,  8,  9])

In [258]:
arr=np.arange(0,10).reshape(5,2)

In [259]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [263]:
arr[:]=100

In [264]:
arr

array([[100, 100],
       [100, 100],
       [100, 100],
       [100, 100],
       [100, 100]])

# Array Slicing (row, column)

In [115]:
# Slicing in Python (and NumPy) includes the start index but excludes the end index 

In [116]:
pizza1=np.random.randint(10,20,5)
pizza2=np.random.randint(1,20,size=(2,3))

In [117]:
print(pizza1)

[12 10 14 19 16]


In [118]:
print(pizza2)

[[14  7  9]
 [15 15 10]]


In [119]:
print(pizza1[1:3])

[10 14]


In [120]:
orders=np.array(['cheese','veg','spicy','bbq'])

In [121]:
print(orders)

['cheese' 'veg' 'spicy' 'bbq']


In [122]:
print(orders[1:3])

['veg' 'spicy']


### 2D Array

In [123]:
pizza2=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

In [124]:
print(pizza2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [125]:
print(pizza2[:,1]) #row all #column 1

[2 5 8]


In [126]:
print(pizza2[1,:]) #row 0 column all

[4 5 6]


In [127]:
print(pizza2 [0:2,0:1]) #first two row and first column


[[1]
 [4]]


In [128]:
print(pizza2 [1:])  # row2 to all

[[4 5 6]
 [7 8 9]]


In [129]:
print(pizza2 [:1])  

[[1 2 3]]


In [130]:
print(pizza2 [2:]) 

[[7 8 9]]


In [131]:
print(pizza2 [:2]) 

[[1 2 3]
 [4 5 6]]


In [132]:
print(pizza2 [1:,1:])

[[5 6]
 [8 9]]


In [133]:
print(pizza2 [:2,1:])

[[2 3]
 [5 6]]


In [134]:
print(pizza2 [:2,:1])

[[1]
 [4]]


In [135]:
print(pizza2 [:2,1:3])

[[2 3]
 [5 6]]


In [136]:
orders2=np.array([['cheese','veg'],['spicy','bbq']])

In [137]:
print(orders2)

[['cheese' 'veg']
 ['spicy' 'bbq']]


In [138]:
print(orders2[0,1]) # Row 0 , Column 1

veg


### 3D array

In [139]:
pizza3=np.array([[[1,2,3],
          [4,5,6],
          [7,8,9]]])

In [140]:
pizza3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [141]:
pizza3.ndim

3

In [142]:
print(pizza3[0,1,2]) #index,row,column

6


In [143]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])


In [144]:
arr

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [145]:
arr[1:3]

array([[ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [146]:
arr[1:3,1:3]

array([[ 60,  70],
       [100, 110]])

In [147]:
arr[1:3,1:3]=0

In [148]:
arr

array([[ 10,  20,  30,  40],
       [ 50,   0,   0,  80],
       [ 90,   0,   0, 120],
       [130, 140, 150, 160]])

# reshape

In [149]:
array=np.random.randint(5,20,size=(2,3))

In [150]:
print(array)

[[16 17  7]
 [19 11  5]]


In [151]:
#method 1
print(np.reshape(array,(3,2))) #np.reshape(name of the array, (new shape (row,column))

[[16 17]
 [ 7 19]
 [11  5]]


In [152]:
#method 2 
print(array.reshape(3,2)) #arrayname.reshape((new shape (row,column))

[[16 17]
 [ 7 19]
 [11  5]]


# resize 

In [153]:
array1= np.random.randint(1,15,size=(3,3))


In [154]:
print(array1)

[[ 4 13  4]
 [14  5  7]
 [ 7 13 11]]


In [155]:
print(np.resize(array1,(5,3))) #method 1

[[ 4 13  4]
 [14  5  7]
 [ 7 13 11]
 [ 4 13  4]
 [14  5  7]]


In [156]:
array1.resize(6,3) #method 2

In [157]:
print(array1)

[[ 4 13  4]
 [14  5  7]
 [ 7 13 11]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0  0]]


# ravel()

In [158]:
arr10=np.array([[2,3,4],[12,13,14]])

In [159]:
arr10

array([[ 2,  3,  4],
       [12, 13, 14]])

In [160]:
print(arr10.ravel())



[ 2  3  4 12 13 14]


In [161]:
ravel= arr10.ravel()

In [162]:
ravel.shape

(6,)

# flatten()
flatten(): Always returns a copy of the original array. Modifications to the flattened array will not affect the original array.

In [163]:
arr11=np.array([[10,20,30],[40,50,60]])

In [164]:
arr11

array([[10, 20, 30],
       [40, 50, 60]])

In [165]:
arr11.flatten()

array([10, 20, 30, 40, 50, 60])

In [166]:
arr12=np.array([[4,5,6],[7,8,9]])

In [167]:
arr12

array([[4, 5, 6],
       [7, 8, 9]])

In [168]:
ravel=arr12.ravel()

In [169]:
ravel

array([4, 5, 6, 7, 8, 9])

In [170]:
flatten=arr12.flatten()

In [171]:
flatten

array([4, 5, 6, 7, 8, 9])

In [172]:
flatten[0]=40

In [173]:
flatten

array([40,  5,  6,  7,  8,  9])

In [174]:
arr12

array([[4, 5, 6],
       [7, 8, 9]])

In [175]:
ravel

array([4, 5, 6, 7, 8, 9])

In [176]:
ravel[0]=40

In [177]:
arr12

array([[40,  5,  6],
       [ 7,  8,  9]])

# repeat

In [178]:
rep=np.array([1,2,3])

In [179]:
np.repeat(rep,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [180]:
np.repeat(rep,3,axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [181]:
rep2=np.array([[1,2,3],[4,5,6]])

In [182]:
rep2

array([[1, 2, 3],
       [4, 5, 6]])

In [183]:
np.repeat(rep2,3,axis=0) #rows

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [4, 5, 6],
       [4, 5, 6]])

In [184]:
np.repeat(rep2,3,axis=1) #columns

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [4, 4, 4, 5, 5, 5, 6, 6, 6]])

# Stacking

### hstack(), column_stack()

In [185]:
a=np.random.randint(1,10,size=(3,3))

In [186]:
print(a)

[[4 7 3]
 [6 2 9]
 [5 6 4]]


In [187]:
b=a*2

In [188]:
print(b)

[[ 8 14  6]
 [12  4 18]
 [10 12  8]]


In [189]:
print(np.hstack((a,b)))

[[ 4  7  3  8 14  6]
 [ 6  2  9 12  4 18]
 [ 5  6  4 10 12  8]]


In [190]:
print(np.column_stack((a,b)))

[[ 4  7  3  8 14  6]
 [ 6  2  9 12  4 18]
 [ 5  6  4 10 12  8]]


### vstack(),row_stack()

In [191]:
a=np.random.randint(1,10,size=(3,3))

In [192]:
print(a)

[[7 9 7]
 [1 1 9]
 [9 4 9]]


In [193]:
b=a*2

In [194]:
print(b)

[[14 18 14]
 [ 2  2 18]
 [18  8 18]]


In [195]:
vstack= np.vstack((a,b))

In [196]:
print(vstack)

[[ 7  9  7]
 [ 1  1  9]
 [ 9  4  9]
 [14 18 14]
 [ 2  2 18]
 [18  8 18]]


In [197]:
#rowstack=np.row_stack((a,b))

In [198]:
#print(rowstack)

### concatenate()

In [199]:
np.concatenate((a,b),axis=0) #effects row

array([[ 7,  9,  7],
       [ 1,  1,  9],
       [ 9,  4,  9],
       [14, 18, 14],
       [ 2,  2, 18],
       [18,  8, 18]], dtype=int32)

In [200]:
np.concatenate((a,b),axis=1) #effects column

array([[ 7,  9,  7, 14, 18, 14],
       [ 1,  1,  9,  2,  2, 18],
       [ 9,  4,  9, 18,  8, 18]], dtype=int32)

### dstack( )

In [201]:
x= np.random.randint(1,10,size=(2,3))

In [202]:
x

array([[3, 7, 6],
       [8, 9, 5]], dtype=int32)

In [203]:
y= np.random.randint(10,20,size=(2,3))

In [204]:
y

array([[10, 12, 19],
       [17, 15, 17]], dtype=int32)

In [205]:
np.dstack((x,y))

array([[[ 3, 10],
        [ 7, 12],
        [ 6, 19]],

       [[ 8, 17],
        [ 9, 15],
        [ 5, 17]]], dtype=int32)

# argmax,argmin

In [206]:
num=np.array([40,20,10,30,50])

In [207]:
print(np.argmax(num)) #index

4


In [208]:
print(np.argmin(num)) #index

2


### max

In [209]:
print(np.max(num)) #index

50


### min

In [210]:
print(np.min(num)) #index

10


# split ()

In [211]:
big_array=np.arange(10)

In [212]:
big_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [213]:
split_array= np.split(big_array,5)

In [214]:
split_array

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [215]:
split_array[1]

array([2, 3])

In [216]:
type(split_array)

list

In [217]:
type(split_array[1])

numpy.ndarray

# searchsorted ()

In [218]:
new_array=[10,20,30,40,50]

In [219]:
positiion= np.searchsorted(new_array,42)

In [220]:
print(positiion)

4


# Where

In [221]:
arr=np.arange(10)

In [222]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [223]:
where_check=np.where(arr%2==0)

In [224]:
where_check

(array([0, 2, 4, 6, 8]),)

# Sort

In [225]:
arr=np.array(['Cherry','Banana','Apple'])

In [226]:
arr

array(['Cherry', 'Banana', 'Apple'], dtype='<U6')

In [227]:
np.sort(arr)

array(['Apple', 'Banana', 'Cherry'], dtype='<U6')

# Conditinal Selection

In [242]:
arr=np.arange(0,10)

In [243]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [244]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [245]:
arr[arr>5]  #this can be used as a conditional selection

array([6, 7, 8, 9])

### File Handling

In [270]:
data=np.loadtxt('data.csv',delimiter=',')

In [271]:
data

array([[1., 2., 3.],
       [4., 2., 3.],
       [7., 2., 3.]])

In [280]:
arr=np.arange(0,50).reshape(10,5)

In [281]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
np.savetxt('output.csv',arr,delimiter=',',fmt='%d')